// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Training_and_Workout_App.DataAccess.Context;

#nullable disable

namespace Training_and_Workout_App.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402172400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.DayPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("DayPlans");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.DayPlanExercise", b =>
                {
                    b.Property<int>("DayPlanId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("DayPlanId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("DayPlanExercises");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GifUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Meals")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.PauseTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<int>("Seconds")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutTrackingStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTrackingStateId")
                        .IsUnique();

                    b.ToTable("PauseTimes");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.QuestionnaireEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("Skipped")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("QuestionnaireEntries");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("WorkoutTrackingStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTrackingStateId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutTrackingState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId")
                        .IsUnique();

                    b.ToTable("WorkoutTrackingStates");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.DayPlan", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.WorkoutPlan", "WorkoutPlan")
                        .WithMany("Days")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.DayPlanExercise", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.DayPlan", "DayPlan")
                        .WithMany("DayPlanExercises")
                        .HasForeignKey("DayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training_and_Workout_App.Domain.Entities.Exercise", "Exercise")
                        .WithMany("DayPlanExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DayPlan");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.MealPlan", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.PauseTime", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.WorkoutTrackingState", "WorkoutTrackingState")
                        .WithOne("PauseTime")
                        .HasForeignKey("Training_and_Workout_App.Domain.Entities.PauseTime", "WorkoutTrackingStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTrackingState");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.QuestionnaireEntry", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.Question", "Question")
                        .WithMany("QuestionnaireEntries")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Training_and_Workout_App.Domain.Entities.User", "User")
                        .WithMany("QuestionnaireEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutPlan", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User", "User")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutSet", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.WorkoutTrackingState", "WorkoutTrackingState")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutTrackingStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTrackingState");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutTrackingState", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.WorkoutPlan", "WorkoutPlan")
                        .WithOne("WorkoutTracking")
                        .HasForeignKey("Training_and_Workout_App.Domain.Entities.WorkoutTrackingState", "WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.DayPlan", b =>
                {
                    b.Navigation("DayPlanExercises");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("DayPlanExercises");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Question", b =>
                {
                    b.Navigation("QuestionnaireEntries");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.User", b =>
                {
                    b.Navigation("MealPlans");

                    b.Navigation("QuestionnaireEntries");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutPlan", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("WorkoutTracking")
                        .IsRequired();
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutTrackingState", b =>
                {
                    b.Navigation("PauseTime")
                        .IsRequired();

                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
