// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Training_and_Workout_App.DataAccess.Context;

#nullable disable

namespace Training_and_Workout_App.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603201743_FixModelSnapshotConsistency")]
    partial class FixModelSnapshotConsistency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Exercise.ExerciseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GifUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.FAQ.FaqCategoryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("FaqCategories");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.FAQ.FaqQuestionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("FaqCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("FaqCategoryId");

                    b.ToTable("FaqQuestions");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.FoodItem.FoodItemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<double>("Grams")
                        .HasColumnType("float");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Kcal")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Popularity")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.MealDayEntry.MealDayEntryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MealPlanIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealDayEntries");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.MealDayEntry.MealDayEntryFoodItemData", b =>
                {
                    b.Property<int>("MealDayEntryId")
                        .HasColumnType("int");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MealDayEntryId", "FoodItemId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("MealDayEntryFoodItems");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.PlanState.PlanActivationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ActivatedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastCycleResetAt")
                        .HasColumnType("date");

                    b.Property<string>("PlanIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlanActivations");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.PlanState.PlanCompletionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateKey")
                        .HasColumnType("date");

                    b.Property<string>("DayToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlanCompletions");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.PlanState.PlanCustomizationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PlanIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlanCustomizations");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.PlanState.UserPlanFavoriteData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlanIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlanFavorites");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.DayPlanData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("DayPlans");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.DayPlanExerciseData", b =>
                {
                    b.Property<int>("DayPlanId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("DayPlanId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("DayPlanExercises");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.MealCategoryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MealPlanDayId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanDayId");

                    b.ToTable("MealCategories");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.MealCategoryFoodItemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<double>("Kcal")
                        .HasColumnType("float");

                    b.Property<int>("MealCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double>("QuantityGrams")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100.0);

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MealCategoryId");

                    b.ToTable("MealCategoryFoodItems");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.MealPlanData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carbs")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Fats")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<int>("Meals")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Proteins")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.MealPlanDayData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.ToTable("MealPlanDays");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.WorkoutPlanData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Question.QuestionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.QuestionnaireEntry.QuestionnaireEntryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("Skipped")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("QuestionnaireEntries");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.User.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.User.UserProfileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("LastActiveDate")
                        .HasColumnType("date");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutHistory.WorkoutCompletionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("int");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalExercises")
                        .HasColumnType("int");

                    b.Property<int>("TotalSets")
                        .HasColumnType("int");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutDayId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutCompletions");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutHistory.WorkoutCompletionExerciseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MuscleGroupSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutCompletionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutCompletionId");

                    b.ToTable("WorkoutCompletionExercises");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutHistory.WorkoutCompletionSetData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("WorkoutCompletionExerciseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutCompletionExerciseId");

                    b.ToTable("WorkoutCompletionSets");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutTracking.PauseTimeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<int>("Seconds")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutTrackingStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTrackingStateId")
                        .IsUnique();

                    b.ToTable("PauseTimes");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutTracking.WorkoutSetData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DayPlanId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int?>("WorkoutTrackingStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTrackingStateId");

                    b.HasIndex("DayPlanId", "ExerciseId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutTracking.WorkoutTrackingStateData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId")
                        .IsUnique();

                    b.ToTable("WorkoutTrackingStates");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.FAQ.FaqQuestionData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.FAQ.FaqCategoryData", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("FaqCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.MealDayEntry.MealDayEntryData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User.UserData", "User")
                        .WithMany("MealDayEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.MealDayEntry.MealDayEntryFoodItemData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.FoodItem.FoodItemData", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Training_and_Workout_App.Domain.Entities.MealDayEntry.MealDayEntryData", "MealDayEntry")
                        .WithMany("MealDayEntryFoodItems")
                        .HasForeignKey("MealDayEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("MealDayEntry");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.PlanState.PlanActivationData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User.UserData", "User")
                        .WithMany("PlanActivations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.PlanState.PlanCompletionData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User.UserData", "User")
                        .WithMany("PlanCompletions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.PlanState.PlanCustomizationData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User.UserData", "User")
                        .WithMany("PlanCustomizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.PlanState.UserPlanFavoriteData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User.UserData", "User")
                        .WithMany("PlanFavorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.DayPlanData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.Plans.WorkoutPlanData", "WorkoutPlan")
                        .WithMany("Days")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.DayPlanExerciseData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.Plans.DayPlanData", "DayPlan")
                        .WithMany("DayPlanExercises")
                        .HasForeignKey("DayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training_and_Workout_App.Domain.Entities.Exercise.ExerciseData", "Exercise")
                        .WithMany("DayPlanExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DayPlan");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.MealCategoryData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.Plans.MealPlanDayData", "MealPlanDay")
                        .WithMany("Categories")
                        .HasForeignKey("MealPlanDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlanDay");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.MealCategoryFoodItemData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.FoodItem.FoodItemData", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Training_and_Workout_App.Domain.Entities.Plans.MealCategoryData", "MealCategory")
                        .WithMany("Items")
                        .HasForeignKey("MealCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("MealCategory");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.MealPlanData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User.UserData", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.MealPlanDayData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.Plans.MealPlanData", "MealPlan")
                        .WithMany()
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.WorkoutPlanData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User.UserData", "User")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.QuestionnaireEntry.QuestionnaireEntryData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.Question.QuestionData", "Question")
                        .WithMany("QuestionnaireEntries")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Training_and_Workout_App.Domain.Entities.User.UserData", "User")
                        .WithMany("QuestionnaireEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.User.UserProfileData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User.UserData", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("Training_and_Workout_App.Domain.Entities.User.UserProfileData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutHistory.WorkoutCompletionData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.User.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training_and_Workout_App.Domain.Entities.Plans.DayPlanData", "WorkoutDay")
                        .WithMany()
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training_and_Workout_App.Domain.Entities.Plans.WorkoutPlanData", "WorkoutPlan")
                        .WithMany()
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutDay");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutHistory.WorkoutCompletionExerciseData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.WorkoutHistory.WorkoutCompletionData", "WorkoutCompletion")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutCompletion");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutHistory.WorkoutCompletionSetData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.WorkoutHistory.WorkoutCompletionExerciseData", "WorkoutCompletionExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutCompletionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutCompletionExercise");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutTracking.PauseTimeData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.WorkoutTracking.WorkoutTrackingStateData", "WorkoutTrackingState")
                        .WithOne("PauseTime")
                        .HasForeignKey("Training_and_Workout_App.Domain.Entities.WorkoutTracking.PauseTimeData", "WorkoutTrackingStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTrackingState");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutTracking.WorkoutSetData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.WorkoutTracking.WorkoutTrackingStateData", "WorkoutTrackingState")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutTrackingStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Training_and_Workout_App.Domain.Entities.Plans.DayPlanExerciseData", "DayPlanExercise")
                        .WithMany("Sets")
                        .HasForeignKey("DayPlanId", "ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DayPlanExercise");

                    b.Navigation("WorkoutTrackingState");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutTracking.WorkoutTrackingStateData", b =>
                {
                    b.HasOne("Training_and_Workout_App.Domain.Entities.Plans.WorkoutPlanData", "WorkoutPlan")
                        .WithOne("WorkoutTracking")
                        .HasForeignKey("Training_and_Workout_App.Domain.Entities.WorkoutTracking.WorkoutTrackingStateData", "WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Exercise.ExerciseData", b =>
                {
                    b.Navigation("DayPlanExercises");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.FAQ.FaqCategoryData", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.MealDayEntry.MealDayEntryData", b =>
                {
                    b.Navigation("MealDayEntryFoodItems");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.DayPlanData", b =>
                {
                    b.Navigation("DayPlanExercises");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.DayPlanExerciseData", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.MealCategoryData", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.MealPlanDayData", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Plans.WorkoutPlanData", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("WorkoutTracking");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.Question.QuestionData", b =>
                {
                    b.Navigation("QuestionnaireEntries");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.User.UserData", b =>
                {
                    b.Navigation("MealDayEntries");

                    b.Navigation("MealPlans");

                    b.Navigation("PlanActivations");

                    b.Navigation("PlanCompletions");

                    b.Navigation("PlanCustomizations");

                    b.Navigation("PlanFavorites");

                    b.Navigation("QuestionnaireEntries");

                    b.Navigation("UserProfile");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutHistory.WorkoutCompletionData", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutHistory.WorkoutCompletionExerciseData", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Training_and_Workout_App.Domain.Entities.WorkoutTracking.WorkoutTrackingStateData", b =>
                {
                    b.Navigation("PauseTime")
                        .IsRequired();

                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
